from __future__ import annotations

from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    LOCALAPPDATA_MISSING = "LOCALAPPDATA_MISSING"
    PATH_TRAVERSAL = "PATH_TRAVERSAL"
    ABSOLUTE_PATH_ESCAPE = "ABSOLUTE_PATH_ESCAPE"
    PATH_OUTSIDE_RUNTIME_ROOT = "PATH_OUTSIDE_RUNTIME_ROOT"
    SYMLINK_ESCAPE = "SYMLINK_ESCAPE"
    PATH_IDENTITY_CHANGED = "PATH_IDENTITY_CHANGED"
    WRITE_DIRECTORY_MISSING = "WRITE_DIRECTORY_MISSING"
    SCOPE_VALIDATION_FAILED = "SCOPE_VALIDATION_FAILED"
    BUSINESS_REPOSITORY_WRITE = "BUSINESS_REPOSITORY_WRITE"
    INVALID_PROJECT_ID = "INVALID_PROJECT_ID"
    ATOMIC_WRITE_FAILED = "ATOMIC_WRITE_FAILED"
    REPOSITORY_NOT_GIT = "REPOSITORY_NOT_GIT"
    REPOSITORY_STATE_CHANGED = "REPOSITORY_STATE_CHANGED"
    RELEASE_LAYOUT_INCOMPLETE = "RELEASE_LAYOUT_INCOMPLETE"
    INVALID_EXECUTION_NUMBER = "INVALID_EXECUTION_NUMBER"
    APPROVAL_SCOPE_CHANGED = "APPROVAL_SCOPE_CHANGED"
    APPROVAL_LEASE_EXPIRED = "APPROVAL_LEASE_EXPIRED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    HIGH_RISK_APPROVAL_REQUIRED = "HIGH_RISK_APPROVAL_REQUIRED"
    CAPTCHA_BYPASS_FORBIDDEN = "CAPTCHA_BYPASS_FORBIDDEN"
    CAPTCHA_MODE_ENVIRONMENT_MISMATCH = "CAPTCHA_MODE_ENVIRONMENT_MISMATCH"
    ADAPTER_POLICY_VIOLATION = "ADAPTER_POLICY_VIOLATION"
    PRODUCTION_EXECUTION_REJECTED = "PRODUCTION_EXECUTION_REJECTED"
    UNKNOWN_ENVIRONMENT = "UNKNOWN_ENVIRONMENT"
    UNAPPROVED_TARGET = "UNAPPROVED_TARGET"
    REDIRECT_REJECTED = "REDIRECT_REJECTED"
    CONCURRENCY_APPROVAL_REQUIRED = "CONCURRENCY_APPROVAL_REQUIRED"
    GOLDEN_REQUEST_FAILED = "GOLDEN_REQUEST_FAILED"
    RESULT_NOT_SERIALIZABLE = "RESULT_NOT_SERIALIZABLE"
    PHYSICAL_DELETE_FORBIDDEN = "PHYSICAL_DELETE_FORBIDDEN"
    CONTROLLED_WRITE_REQUIRED = "CONTROLLED_WRITE_REQUIRED"
    SQL_READ_ONLY_VIOLATION = "SQL_READ_ONLY_VIOLATION"
    SECRET_VALUE_FORBIDDEN = "SECRET_VALUE_FORBIDDEN"
    STATE_NOT_FOUND = "STATE_NOT_FOUND"
    INVALID_PROJECT_STATE = "INVALID_PROJECT_STATE"
    EXCEL_SHEET_CONTRACT = "EXCEL_SHEET_CONTRACT"
    EXCEL_DEPENDENCY_MISSING = "EXCEL_DEPENDENCY_MISSING"
    STAGE_A_CONTRACT_INVALID = "STAGE_A_CONTRACT_INVALID"
    STAGE_A_STATE_INVALID = "STAGE_A_STATE_INVALID"
    STAGE_A_SELECTION_INVALID = "STAGE_A_SELECTION_INVALID"
    STAGE_A_PLAN_PACKAGE_INVALID = "STAGE_A_PLAN_PACKAGE_INVALID"
    STAGE_A_SELECTION_STALE = "STAGE_A_SELECTION_STALE"
    STAGE_A_SELECTION_EXISTS = "STAGE_A_SELECTION_EXISTS"
    STAGE_A_ANALYSIS_V2_REQUIRED = "STAGE_A_ANALYSIS_V2_REQUIRED"
    STAGE_A_PLAN_EVIDENCE_CONFLICT = "STAGE_A_PLAN_EVIDENCE_CONFLICT"


class RuntimePolicyError(Exception):
    def __init__(
        self,
        code: ErrorCode,
        message: str,
        *,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}

    def as_dict(self) -> dict[str, Any]:
        return {
            "status": "error",
            "error_code": self.code.value,
            "message": self.message,
            "details": self.details,
        }
